name: CI/CD pipeline test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


permissions:
  contents: read


env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
  AWS_HOST: ${{ secrets.AWS_HOST }}
  AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: $DOCKER_REPO:latest
          context: $DOCKER_REPO


  deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Check out the repo
         uses: actions/checkout@v3

       - name: EC2 Docker Deploy
         uses: appleboy/ssh-action@master
         with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_SSH_KEY }}
          script: |
            cd git-action-test/
            docker pull ${{ secrets.DOCKER_ID }}/cicd:latest
            docker tag app ${{ secrets.DOCKER_ID }}/cicd:latest
            docker stop app
            docker rm app
            docker rmi ${{ secrets.DOCKER_ID }}/cicd:latest
            docker network create -d bridge test
            
            docker stop mysqlDB
            docker rm mysqlDB
            docker rmi mysqlDB
            docker run -d --network test --network-alias mysql -v  /build/DB/mysql:/var/lib/mysql --name mysqlDB -e MYSQL_DATABASE=anonymous_board -e MYSQL_USER=user01 -e MYSQL_PASSWORD=user01 -e MYSQL_ROOT_PASSWORD=password -p 3306:3306 mysql

            docker run -d --rm --name app --network test -p 8080:8080 ${{ secrets.DOCKER_ID }}/cicd:latest
