name: CI/CD pipeline test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
  AWS_HOST: ${{ secrets.AWS_HOST }}
  AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Push to Docker Hub
        run: |
          docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ env.DOCKER_HUB_ACCESS_TOKEN }}
          docker build -t app .
          docker tag app ${{ env.DOCKER_REPO }}:latest
          docker push ${{ env.DOCKER_REPO }}


      - name: EC2 Docker Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_SSH_KEY }}
          script: |
            cd git-action-test/
            docker pull ${{ env.DOCKER_REPO }}:latest
            docker-compose down
            docker-compose up -d
            