name: CI/CD pipeline test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
  AWS_HOST: ${{ secrets.AWS_HOST }}
  AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
  AWS_USER: ${{ secrets.AWS_USER }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_REPO }}:latest .
          docker push ${{ env.DOCKER_REPO }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: EC2 Docker Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_SSH_KEY }}
          script: |
            cd git-action-test/
            sed -i 's|image:.*|image: '"${{ env.DOCKER_REPO }}:latest"'|' docker-compose.yaml
            docker-compose down
            docker-compose pull
            docker-compose up -d
