name: CI/CD pipeline test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


permissions:
  contents: read


env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
  AWS_HOST: ${{ secrets.AWS_HOST }}
  AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}


jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_REPO }}:latest
          context: ${{ env.DOCKER_REPO }}


  deploy:
     #runs-on: ubuntu-latest
     runs-on: self-hosted
     steps:
       - name: Check out the repo
         uses: actions/checkout@v3

       - name: EC2 Docker Deploy
         uses: appleboy/ssh-action@master
         with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_SSH_KEY }}
          script: |
            cd git-action-test/

